# Generated by Django 6.1 on 2026-08-29 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, default='')),
                ('meta_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=150)),
                ('bio', models.TextField(blank=True, default='')),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('target_role', models.CharField(blank=True, default='Full Stack & AI Engineer', max_length=100)),
                ('skills_list', models.JSONField(blank=True, default=list)),
                ('github_url', models.CharField(blank=True, default='', max_length=300)),
                ('github_username', models.CharField(blank=True, default='', max_length=100)),
                ('github_avatar_url', models.CharField(blank=True, default='', max_length=500)),
                ('github_bio', models.TextField(blank=True, default='')),
                ('github_company', models.CharField(blank=True, default='', max_length=150)),
                ('github_location', models.CharField(blank=True, default='', max_length=150)),
                ('github_public_repos', models.IntegerField(default=0)),
                ('github_followers', models.IntegerField(default=0)),
                ('github_following', models.IntegerField(default=0)),
                ('github_top_languages', models.JSONField(blank=True, default=list)),
                ('github_top_repos', models.JSONField(blank=True, default=list)),
                ('github_last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
