# Generated by Django 6.1 on 2026-08-31 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleLessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.CharField(db_index=True, max_length=100)),
                ('module_id', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('topic', models.CharField(blank=True, default='', max_length=200)),
                ('lesson_markdown', models.TextField()),
                ('learning_objectives', models.JSONField(blank=True, default=list)),
                ('code_examples', models.JSONField(blank=True, default=list)),
                ('key_takeaways', models.JSONField(blank=True, default=list)),
                ('assignment_prompt', models.TextField()),
                ('assignment_starter_code', models.TextField(blank=True, default='')),
                ('assignment_criteria', models.JSONField(blank=True, default=list)),
                ('exam_questions', models.JSONField(blank=True, default=list)),
                ('exam_answer_key', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'skill_id', 'module_id')},
            },
        ),
    ]
