# Generated by Django 6.1 on 2026-08-31 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_modulelessoncontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringSessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('session_type', models.CharField(max_length=60)),
                ('target_name', models.CharField(max_length=200)),
                ('status', models.CharField(default='active', max_length=40)),
                ('outcome', models.CharField(default='in_progress', max_length=40)),
                ('exam_score', models.FloatField(blank=True, null=True)),
                ('integrity_score', models.IntegerField(default=100)),
                ('is_terminated', models.BooleanField(default=False)),
                ('termination_reason', models.CharField(blank=True, default='', max_length=300)),
                ('audit_trail', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
