# Generated by Django 6.1 on 2026-08-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_proctoringsessionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verified_projects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
